### ISSUE TITLE
browser.assert.textContains method is not allowing string arrays as parameter

### ISSUE THREAD

**Issue by facusantillo** [angrykoala/wendigo#458]
According to documentation, textContains method allow the use of string arrays. 

Looking into the code, signature parameters are set as `string`. Should be set as `string | string[]` so we can use arrays on it, unless I missunderstand something.

**Comment by angrykoala** [comment]
Hi @facusantillo 
Indeed, the signature value is wrong (good catch :clap:), this method (and the .not counterpart) both support array as described in the docs.

The following test exists confirming this behavior:
```js
    it("Multiple Texts in Array With Regex", async() => {
        await browser.assert.textContains("p", ["My first", "My second"]);
        await browser.assert.textContains("p", ["My first"]);
    });
```

This will son be fixed in the dev branch and will be available in the release 2.13.0

**Comment by facusantillo** [comment]
@angrykoala thx. I'll handle it manually for now.

Also, how do you handle, for example, having an array of elements returning texts, and asserting if they contains at least one of the elements on another array?

Take the next example: 

email_elements = [class='emails'] => returning array of DOMElements with emails text

emails = string[] => array of emails send. At least ONE of the elements on the email_elements should match ONE of the emails in the string[].

Would you like to include some method receiving a WendigoSelector[] and assert if contains some of the elements on a string | string[] ? Would be very helpful in cases like this one.

**Comment by angrykoala** [comment]
@facusantillo Currently no method input supports an array of DomElements (this is due to a combination of poor performance in some methods, complexity on defining the behaviour itself or simply due to a lack of need of this feature).

So, for now, your best options would be to either use a common selector query that catches all those elements or an loop making the assertion for each element. :cry: 

With that said, I've made a quick check and I see no real limitation on adding support for WendigoSelector[] in the method textContains, if this feature is useful to you, please consider creating a new issue with a description, some examples in javascript/typescript would be appreciated as well so I can understand the desired behaviour and I'll try to keep you updated on that feature there :smiley:
